### ISSUE TITLE
Include dependencies when deploying

### ISSUE THREAD

**Issue by jdemaeyer** [scrapinghub/shub#123]
`deploy` should be "run and forget": `shub` should make sure that all requirements the project has (specified in `requirements.txt` or `setup.py`'s `install_requires`) are available on Scrapy Cloud and upload them if necessary.

See also #56.

**Comment by jdemaeyer** [comment]
We're dropping this for now as there are a few issues with binary eggs needing to be built server-side

**Comment by josericardo** [comment]
Just for the record, ideally this is good. In practice, though, some projects can break if the deps are updated all the time. Projects that have git dependencies, for example, can break because of a bad commit on the dep.

More commonly, we have old projects that rely on old dep versions. If we do a quick fix and the deps are accidentally  updated it may cause a lot of trouble, hehe.
