### ISSUE TITLE
Allow scheduling custom scripts

### ISSUE THREAD

**Issue by jdemaeyer** [scrapinghub/shub#160]
http://doc.scrapinghub.com/scrapy-cloud.html#running-custom-python-scripts

**Comment by eliasdorneles** [comment]
This would be lovely! :)
We've been using a custom script in an internal project for this.

**Comment by vshlapakov** [comment]
The issue is quite old: scheduling custom scripts is supported for a long time, the only difference is to add `py:` prefix to the name of the script and provide it as a spider name on scheduling, like ` shub schedule py:testargs.py`, it described well [here](https://support.scrapinghub.com/support/solutions/articles/22000200394-running-custom-python-scripts) with exampes.

**Comment by andrewbaxter** [comment]
Sorry to dredge up a closed issue :)

Is this something that could go in the documentation?  I read through that QA but there wasn't a `shub` example and it's not clear how to translate the command arguments into shub arguments.  I tried `-a` just in case but the job started with no arguments.
