### ISSUE TITLE
Deploy failed because multiple spiders (?)

### ISSUE THREAD

**Issue by AxelEriksson0** [scrapinghub/shub#273]
Hi!

First time bug reporting / issue reporting.

I've deployed several spiders successfully but this is my first time running two spiders with two different pipelines in the same project (as shown - http://stackoverflow.com/questions/36173503/scrapy-put-two-spiders-in-single-file)

It works running locally but deploying to Scrapinghub.com doesn't work. See the errors below.

>>> Checking python dependencies
No broken requirements found.
>>> Getting spiders list:
WARNING: There're some errors when listing spiders:
Exceeded container timeout 60s
{"message": "List exit code: -1", "details": null, "error": "build_error"}

{"message": "Internal build error", "status": "error"}
Deploy log location: /tmp/shub_deploy_uENZvE.log
Error: Deploy failed: {"message": "Internal build error", "status": "error"}

I thought that maybe it's that I'm missing CrawlerProcess and tried importing in in requirements.txt, then I get requirements error.

Collecting pymysql (from -r /app/requirements.txt (line 1))
  Downloading PyMySQL-0.7.11-py2.py3-none-any.whl (78kB)
Collecting CrawlerProcess (from -r /app/requirements.txt (line 2))
  Could not find a version that satisfies the requirement CrawlerProcess (from -r /app/requirements.txt (line 2)) (from versions: )
No matching distribution found for CrawlerProcess (from -r /app/requirements.txt (line 2))

{"message": "The command '/bin/sh -c sudo -u nobody -E PYTHONUSERBASE=$PYTHONUSERBASE     pip install --user --no-cache-dir -r /app/requirements.txt' returned a non-zero code: 1", "details": {"message": "The command '/bin/sh -c sudo -u nobody -E PYTHONUSERBASE=$PYTHONUSERBASE     pip install --user --no-cache-dir -r /app/requirements.txt' returned a non-zero code: 1"}, "error": "requirements_error"}

{"message": "Requirements error", "status": "error"}
Deploy log location: /tmp/shub_deploy_zlQUiK.log
Error: Deploy failed: {"message": "Requirements error", "status": "error"}

Any ideas or should I perhaps split the project in two separate spiders (even though they are related).

**Comment by jdemaeyer** [comment]
Hey Axel, thanks for the report!

Having two spiders in the same file also works on Scrapy Cloud (scrapinghub.com). However, you won't be able to control how the spider is started on Scrapy Cloud. I.e., you cannot start your own `CrawlerProcess`.

From looking at the StackOverflow question you mentioned my guess is that in one of your files (presumably the one containing the spiders), you initiate a `CrawlerProcess` instance and try to call its `start()` method, is that correct?

What happens when you try to deploy is that Scrapy Cloud tries to run `scrapy list` in your project to get a list of the available spiders. While importing the spider module it then finds and executes your `CrawlerProcess` code, which starts the crawl (even though we only wanted to get a list of available spiders). The crawl takes a bit and that's why you get "Exceeded container timeout 60s".

There are two easy ways to fix this:

1. Move the `CrawlerProcess` code into a separate Python file and just import your spiders from there.
2. Put your `CrawlerProcess` code under a `if __name__ == '__main__':` condition, so that your file looks like this:
    ```
    import scrapy
    from scrapy.crawler import CrawlerProcess

    class MySpider1(scrapy.Spider):
        # Your first spider definition
        ...

    class MySpider2(scrapy.Spider):
        # Your second spider definition
        ...

    if __name__ == '__main__':
        process = CrawlerProcess()
        process.crawl(MySpider1)
        process.crawl(MySpider2)
        process.start() # the script will block here until all crawling jobs are finished
    ```

Generally, you should reconsider if you really need the two spiders to be run in the same process. Maybe it would be enough to have two separate processes running in parallel?

Let me know if this helped :)

**Comment by AxelEriksson0** [comment]
Thanks!!

Yeah, I guess it's generally better to split up the spiders (why though, goes faster to have multiple processes running every individual spider and it's a better overview to have every project individually?)

I did suggestion 2 and it worked great!

**Comment by jdemaeyer** [comment]
@AxelEriksson0 Glad it worked :)

It's not necessarily about splitting up the spider code. If the spiders are somehow related (e.g. they share some code or structure) it makes perfect sense to have them in the same Python module (file). It's about splitting up the _crawls_. While each spider is crawling its target website, the two have no dependency on each other, and therefore it makes sense to run them in separate processes. 

This way, if something weird happens in the first crawl it won't affect the second crawl. And if you want to debug something in the second crawl you won't have to sift through all the log messages from the unrelated first crawl.

**Comment by motogod** [comment]
Hi,
I have the same issue `Exceeded container timeout 60s
`
I am not sure how to use first solution, so i fix my code like this:
i```
f __name__ == '__main__':
    process = CrawlerProcess(get_project_settings())

    for spider in CrawlersArray:
        process.crawl(spider)
            
    process.start()
```

It can be deployed to scrapinghub now, but i find that not any spider run.

Why ?  

Any help would be appreciated. Thanks in advance.
